import type { ProphetArticle } from "./types";
import cannabis from "../../assets/cannabis_integration.jpg";
import sameer from "../../assets/sameer1.jpg";

export const JOHN_HENDERSON_ARTICLE: ProphetArticle = {
  episode: "EPISODE #01",
  date: "WEDNESDAY, 26 NOVEMBER, 2025",
  interviewee: "Sameer Kazmi",

  headline: "Small Talk is not real Conversation:",

  body: [
    "Why don’t you write a book? </br>he asked me —  sitting at Mensa on a rainy day when the sun kept slipping through in the last breath of summer.  “You could be a writer. *With a master's degree.*”  And now… here we are.  Life takes sudden turns we never plan for.  We’re surrounded by people — classmates, colleagues, friends —  but how many do we actually *know*?  We ask:  “How was your weekend?”  “What did you have for lunch?”  But we rarely ask:  “What’s been heavy on your heart lately?”  “What excites you so much you lose track of time?”  Sometimes a stranger appears and suddenly — without warning —  you find pieces of yourself in their story.  Campus life is strange like that.  There are so many familiar faces —  surely we’ve stood in line at Netto together,  sat at opposite ends of the same library table,  shared a nod on the bus.  And over time, we draw silent sketches of each other:  a glance here, an outfit there,  a vibe we *think* we understand.  But we don’t.  Until we talk.  And suddenly —  we realize we share the same questions.  “How do I finish this degree?”  “When will I get that job?”  “Will I ever feel like I belong here?”  Our paths *look* the same.  But they’re not.  That’s the beauty of it.  On a planet orbiting a star 1.3 million times bigger than itself,  in a galaxy with 100 billion stars,  among 2 trillion other galaxies we’ve only *begun* to map...  We still walk the same hallways.  Sit on the same benches.  Order the same Mensa coffee.  But one person’s walking to forget.  Another’s walking to *prove* something.  Some of us are chasing dreams.  Some are just surviving the week.  It looks the same.  But it’s not.  That’s why we talk.  And not just because there’s space and we need to fill it —  but to listen.  To catch the tremble in someone’s laugh.  To hear the part they didn’t say out loud.  To sit beside their silence and still feel close.  We talk to feel less alone in this spinning chaos —  To say, “Hey, I’ve been there.”  Or better yet —  *“Tell me more.”*  And maybe that’s why…  **Small talk was never really small.**",
    "Do you have a passion? Do you pursue it? I used to think writing was mine. But I didn’t realize then that having a passion doesn’t just mean thinking about what you’d like to do in your free time.It means building your life around it. I believe that when you follow your passion — truly — life starts to make a little more sense. Decisions get clearer. The grind feels lighter. You stop surviving and start living. His passion is games. Not just playing them — but creating them. Taking an idea from his mind, shaping it, designing it, and turning it into something you can feel, control, explore. He grew up in Karachi — the third-largest city in the world — a place where life often feels more about making it through the day than dreaming big. Where choosing survival over creativity is the norm. But he didn’t want to be just another product of the system. He held onto his passion like a compass. And that compass brought him to Germany. Here, he studied, worked in the industry for two years — soaking in everything he could. And now? Now he’s building something of his own. A startup. A dream he’s shaping line by line, frame by frame, into a world we can one day play through.",
    "I will start the recording now, I told him.Placed my phone in the middle of the table. Two chairs across each other. Group Room 3 of the campus library.And I felt it — the tension. Crawling up into my body like a guest I didn’t invite.You’re ready, Mesum, I told myself. Deep breath.Exhale it out.Take control now, I mumbled under my breath.Then I looked up and asked the first question.And just like that — I saw the stress leap across the table into him.His body shifted. Arms dropped from the desk to his knees. Back stiffened. He looked at me like I’d asked something heavier than I did.Relax, I said. It’s not an interrogation. I just want to talk.And in that tiny pause, my brain flicked a question back at me:Why’s he nervous? Shouldn’t I be?Humans are weird.I’m the one hosting the interview, the one who’s been thinking about this for weeks — but he’s the one being seen. He’s the one on record. Being listened to, maybe later being read by people he doesn’t even know. People tense up when they’re about to share parts of themselves — even when they’re just talking to a friend.",
  ],
  afterword: {
    title: "Trust the process:",
    body: [
       "There’s a kind of silence you only hear when you stop fighting the moment.Not the silence of giving up — the silence of accepting. Like stepping into an old temple you didn’t build, but somehowrecognize. The air is heavy. The walls are carved with stories of people who came before you. And you realize: they didn’t know the ending either. They just kept walking. Torch in hand. One step. Then another. Because life has a strange way of humbling you right after it crowns you.He told me about the high — being a student, then landing the full-time job, the feeling of “I made it.” The kind of high where you start believing this version of your life is permanent. And then the drop came. Job gone. Stability gone. The neat little narrative shattered. And suddenly, he was back at the beginning — not as punishment, but as placement. Like life saying: You’re not done becoming who you’re supposed to be." ,
       "And that’s where trust gets tested.Because the mind wants guarantees. It wants signs, timestamps, a map. But life doesn’t speak in spreadsheets. It speaks in seasons. In doors that close so you stop walking into the wrong room. In losses that hurt because they detach you from an identity you were holding too tightly.I believe we’re not randomly dropped into our lives. I believe we arrive here through choices — some loud, some quiet, some made for us, and some made by our habits. If someone is poor and someone is rich, it’s not because the universe is playing favorites. Most of the time it’s because one person repeated the hard things longer. Took the hits. Stayed in motion. The other stayed still — or stayed distracted — or never learned how to believe in themselves long enough to build.That sounds harsh. But it’s also a spell of its own: if your actions brought you here, your actions can take you somewhere else.And still… I also believe this: everything happens for a reason.Not the cute kind. The real kind. The kind you only understand later, when you look back and realize that the worst detour was the road that trained you. That the loss wasn’t a curse — it was a correction. That the low wasn’t the universe punishing you — it was the universe preparing you.Sameer’s low didn’t erase him. It revealed him.So maybe trusting the process is this: moving forward even when the meaning hasn’t arrived yet. Lighting the next inch of the path with whatever you have — discipline, faith, a friend’s voice, a half-finished plan. And believing that the fog isn’t there to stop you.It’s there to teach you how to walk without seeing.And if you’re in that fog right now… listen closely.Your life isn’t falling apart.It’s being rewritten — into something truer than what you would’ve chosen if you had stayed comfortable."
    ],
  },
  extendedBody: {
    title: "The Horizon",
    image: {
      src: sameer,
      alt: "Notebook and recorder set up mid-interview",
    },
    body: [
        "By the time the conversation started to soften, the room felt different.Not louder. Not more exciting. Just… truer. Like something invisible had finally sat down between us. Sameer’s shoulders weren’t as guarded anymore. My own mind stopped sprinting ahead. The questions became less like “content” and more like keys — opening doors we didn’t know we were standing in front of.And that’s when I realized what we had actually done.We didn’t defeat small talk.We walked through it.Because maybe small talk is just the lobby. The polite knock. The “are you doing okay?” that sounds casual, but sometimes is the only safe way a person knows how to ask for connection. Maybe it was never useless — maybe it was simply incomplete. A doorway that most people don’t enter because they’re scared of what they might find inside: the truth.",
        "And the truth is always a little messy.It has accents. Breaks. Long pauses. A strange laugh at the wrong time. It has the weight of a job lost right after you thought life was finally stable. It has the quiet fear of starting again, when you’ve already told everyone you were “doing great.” It has the mental noise that follows you to your pillow — even after a long day of pretending you’re fine.Sameer talked about the low like someone who has stared at it long enough to stop flinching.We didn’t romanticize it. We didn’t turn it into a motivational poster. We just named it: the fall, the rebuild, the strange faith required to keep going when the world is no longer clapping for you.And somewhere in the middle of that, cannabis entered the room — not as a headline, but as a mirror.Not “weed is bad” or “weed is good.”But the question underneath: What are we using it for?An escape route? Or a ritual? A hiding place? Or an integration?Sameer’s point stayed with me: the real danger isn’t the joint — it’s the moment you need it just to feel okay. Because when something becomes your daily exit door, life stops teaching you. Pain stops speaking. Growth gets postponed. And you can’t build a life while constantly stepping outside of it.Maybe that’s why this episode had to end here — at the place where honesty becomes a decision.Because conversation, real conversation, is not entertainment.It’s a return.It’s two people sitting across a table saying, in a hundred small ways: I’m here. I’m listening. I won’t reduce you to a headline.And as we packed up — phone off, chairs moving, the library going back to being just a library — I kept thinking:We’re all walking around with whole universes inside us.And most days, we offer each other a teaspoon.So if there’s one thing I want you to take from this, it’s simple:Start with small talk, if that’s all you have.But don’t live there.Ask one real question. Hold the silence. Let the answer breathe.Because the moment someone feels safe enough to tell you the truth…that’s not small talk anymore.That’s the beginning of something that can actually change a life.",
    ],
  },
  favoriteBook: {
    title: "Favourite book",
    gif: {
      src: "https://i.gifer.com/82WK.gif",
      alt: "Looping animation of pages turning inside a warm-lit book",
    },
    body: [
      "After we packed up, I asked Sameer about the stories that steadied him when life felt heavy. He pulled out a worn copy of his favourite novel — the one he rereads whenever he needs a reminder that rebuilding is possible.",
      "He said the book isn’t just a plot to escape into; it’s a map back to himself. Every chapter is a checkpoint: a reason to slow down, breathe, and remember that the journey matters more than the finish line.",
    ],
  },
  sidebar: {
    title: "Hot News ❤️‍🔥" ,
    items: [
      {
        img: cannabis,
        title: "Integration, not escape:",
        text: "weed shouldn’t be a daily hiding spot, but a conscious, limited part of life — a tool you choose, not a crutch you need.",
      },
      {
        title: "When asked about integration of weed in people's life",
        text: "Samir argues not for quitting weed forever, but for integrating it into life without letting it become an escape route. For him, the real problem isn’t the joint — it’s when you need it just to feel okay, instead of facing what life is trying to teach you.",
      },
    ],
  },
  };